apiVersion: v1
kind: Secret
metadata:
  name: ros-certs
  namespace: kube-system
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWRENDQWp5Z0F3SUJBZ0lVSUhvSnRqWEFaQUpCSjJoZXhoUWdicVlqM0FFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0RURUxNQWtHQTFVRUF3d0NZMkV3SGhjTk1qQXdPREU1TURNME9UQXdXaGNOTWpVd09ERTRNRE0wT1RBdwpXakFTTVJBd0RnWURWUVFERXdkeWIzTXRjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCCkNnS0NBUUVBeDlwOTljQ2R5UHBvMC9VWWx0NXJtTDBVZ2RCNTRjMTNucmxMOFdBZUt5N2taekdxbVBFK0NNY2YKTzBpdGxzMEdGWXBoSmxXSk95VmxyY1QzYlZuclB0N25ySGN1MjZNWjJibC9KNGlYNkJMdm45UDZIdFRsSTMwVwpka2pleWxpV0U1M2RNYnBURzRoUVBEUC83Zld5a2NqN05ETlhNQ0ZQVlhCMXdFdGV2WU9UaVppM0pSa3h6SmQ5CkUyQXkyZ2oxUGlsaUFkTWRCaG1JUDE3Q1AzS0wxMVovc29hcStDT0dHWENkSDUyWTVRZ2hpQmJTQ0p1bTZUQkgKTGZRRWVaNmhLTm4rem9XVnhBNUxrRWh0c0VrS0NHeVI2TFdHazJnMllVVVVjSUpLWTlySEpIR3JCb0lvTGtYaQo5bHpWYUxRNkJhWGhFUWtDTWlHT2QxL3RYcm5HSlFJREFRQUJvNEdtTUlHak1BNEdBMVVkRHdFQi93UUVBd0lGCm9EQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUTkVPd3BFNzB0dVpPWkNwazVpa3M2U1pETi9UQWYKQmdOVkhTTUVHREFXZ0JUU013dlpadzdaTTlMRlV6aGIxdUJQdlVrVlBUQkRCZ05WSFJFRVBEQTZnaE55YjNNdApjM1pqTG10MVltVXRjM2x6ZEdWdGdoZHliM010YzNaakxtdDFZbVV0YzNsemRHVnRMbk4yWTRjRUNpc0EvNGNFCkNtQUEvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBU3JPTXFiT3AxSXhPOXVTbTZBSzJnV3k4RDJ6RjRNSWsKKzF2Z0huTXZuOHBkUjNNUEVENFkrUDRKUTBYUUpuWG0rNXdyQ2lnQUIvcTJiR21EdjlCRnFielZUeVBzemVreQpwY0Z0QnpsellFaGwra2MxbmtnUCtUVDkxeTVDRUdaUGdmMHZ2ZTlCSm9maHlDcGI5eUo1d3FNdWNNSkRsR0VYCkJmM3hXMThOKzJNaG5wcnl0U0pib2dJN0VwcjZrOVg3Z2VEWFF1amtuWVhTT1g2WEdIbE0yOUl5TkVkNUlCTCsKNURNbU9iMFlNd3BFY3lmaGFYRmpIZ0RCTkpjSmpTemhFb3ZhOHU5SzFTUnR2endJTmZiT1VlVGJoejdLWlNFTgpyWGowRWFJU3NoaU9VbHFVUC9XcHRlMVdnQW5pd0FabjBTZUE3b2R3QlZwNEZndVp6aERHb0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeDlwOTljQ2R5UHBvMC9VWWx0NXJtTDBVZ2RCNTRjMTNucmxMOFdBZUt5N2taekdxCm1QRStDTWNmTzBpdGxzMEdGWXBoSmxXSk95VmxyY1QzYlZuclB0N25ySGN1MjZNWjJibC9KNGlYNkJMdm45UDYKSHRUbEkzMFdka2pleWxpV0U1M2RNYnBURzRoUVBEUC83Zld5a2NqN05ETlhNQ0ZQVlhCMXdFdGV2WU9UaVppMwpKUmt4ekpkOUUyQXkyZ2oxUGlsaUFkTWRCaG1JUDE3Q1AzS0wxMVovc29hcStDT0dHWENkSDUyWTVRZ2hpQmJTCkNKdW02VEJITGZRRWVaNmhLTm4rem9XVnhBNUxrRWh0c0VrS0NHeVI2TFdHazJnMllVVVVjSUpLWTlySEpIR3IKQm9Jb0xrWGk5bHpWYUxRNkJhWGhFUWtDTWlHT2QxL3RYcm5HSlFJREFRQUJBb0lCQUNxUzMreGZPUDJjWW9KcwpudTFjdWwwU1FuRVpBUzNhQUZaK3NLL2R3dTkrRU1mdTY2R2pHb3p5SmpRUjJuRGFnaVpLa1VHQ1RUYWRVOWk5CnNkdklvUFdHdEtHbnpnS1o3eUxUZ2tQZ3RFT0s3U01HSEMwL093VGhXOHljMzJFSm1BYmJ4VWdYb2lhbVZqbE0KOW9NeHFQV25jK1A5MzkvdjZKK1IwblBCV3BCU08yeVAweWN3eUxGTnJHVW5YYzN4QjJKSkFmRHkwVng5c3NpcAo4bVlJeGdyS05VTXdUL0E5L2VmZWdPVWd4WHNTRTB2MmdkbnNsUVU1N011VllQUGRpYnNSSFZORVpNQkZkWDE0Ck5IUUxUZW1qSUxHdC9rVFYyZVh1eEgzK1ZKbFM2WCtpeldIWDZBcVdqOTNCYmxJSzc4d1l6TmNDQ0pRNmZVcUIKK1hVQ3dxMENnWUVBemd0VG1JUHVvQkJ3WEp5Sk55WnZXNzkveVFuVGpoMnhwZmV0NmJ5dWNIb21VYVZHT0tWYgo2T0RPZVBUQW91MzVCNzJERlR1QTRnS2N3WmdBTEM5SDNZZk14NHRVdjNxM0JsekRJMGZHTWsvK1RLRTUyOUFOCi9YRTh2Y0RpNEFhZ3E2dmFiczhJQUlCUDZSVXNCU01XMFcxNXlTbWprOTJFMTF3SnFpbE9vWDhDZ1lFQStFN3IKZWUyZEVQMmdkNGZPUVhMM1FncDBmWEl1UmxNOElKVHkyMmlLa0l0TTk3c2NWczdaQ0FrZGYwb3Jqem9XanAxRgpQYmdqUGVQdnozMzIvUzMyZ045QXZDM01BSy96SXpBVU5ZU2dPQkFpaUpqZUZPR2JId2dkYXd0VUNsYzRzdGwrCnhncmxKdjMwQmlqVHZBNWNoSUNkNlRqUVhFT1Rkc2dITFRSc29sc0NnWUFFdGFtUmdPS0JjaDYvWHl5YndCc24KZzdjT0IxVjRtQ0VwWkFIcnA4NXM3NzNVZSt5Zyt0YWcraEorSFVvUjcxS1Q1TGNNVXpIYytLWlFub0xTZjdvcQp6Q0hZSmMwb0cwdjNyME1lbVZOa2J3T25DTUJqejl1aUFXYWNCNzZuMUQ3ejdaZXVsTGpnR2c2NWl5eFlhYmJwCnpwRE1FbEdVM2FsZHF0TGx1cy83VFFLQmdRRFZvUkIybGpmTHBtbW9iTzdHNEdKYUx5U0p5UEtIRHBWc2NybCsKaXpLcnFTMU85V3dzUTBuMTMrSEE0YzhZS3FHOWtSRkJTR3NKbEZGOThxSE1zUDZqWVhBUWRsWk5RUk90OG05dwptK284VWFWa1lDQ3hWbWhmQ2x4RS9Eb1JxM2pjWnNMckgvU0cxM1phMWtWVVJnYlMrTlRqRWo0eEl2SjcveHd0CmlDenVnUUtCZ0JUN3JFdzI0MnJBMjcyV2dtVUE5c05xWXV1QWE2TzhXS3VlK0hzQjFVZndGaDlEaENuTWFOTEYKcy9uWFJTYjh4eEpGUmVyY29aMzNuc3I2OGZQWnp3WndhRXhGeEhhcGRoQXVXSkgvVTlEbmFUUndBSGNFSUZHcwpzblhMUmEvem9Gb0R1aXdmS3ptalZtZ09pT1FOZUxib21XRmg5TFByOFFOOWwrL0ltOFc4Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ros
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ros-cluster-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: ros
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros
  namespace: kube-system
  labels:
    app: ros
spec:
  selector:
    matchLabels:
      name: ros
  template:
    metadata:
      labels:
        name: ros
    spec:
      serviceAccountName: ros
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: ros
        image: ubuntu:20.04
        command: [ "/usr/sbin/ros"]
        ports:
          - name: https
            containerPort: 443
        volumeMounts:
        - mountPath: /usr/sbin/ros
          name: ros-vol
        - mountPath: /var/run/serving-cert
          name: ros-serving-cert
      volumes:
      - name: ros-vol
        hostPath:
          path: /etc/edge-ai/scheduler/ros
      - name: ros-serving-cert
        secret:
          secretName: ros-certs
---
kind: Service
apiVersion: v1
metadata:
  name: ros-svc
  namespace: kube-system
  labels:
    app: ros-svc
spec:
  selector:
    name: ros
  clusterIP: 10.96.0.255
  ports:
  - name: https
    port: 443
    targetPort: https
