apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
   kubeconfig: "/etc/kubernetes/scheduler.conf"
schedulerName: my-scheduler
algorithmSource:
  policy:
    file:
      path: "/etc/edge-ai/scheduler/sched-policy-k8s.json"
